name: GitHub Actions Demo
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        if: always()
        run: npm run build
      - name: unit test
        if: always()
        run: npm run test
      - name: Lint code
        if: always()
        run: npm run lint
